config_tests = {
    1 : {
            "number_of_nodes" : 4,
            "number_of_twins" : 1,
            "rounds" : 7,
            "number_of_partition" : 3,
            "leaders_only_faulty" : False,
            "number_of_partitions_pruned" : 4,
            "selection_type_for_partitions" : "RANDOM",
            "number_of_partitions_leaders_pruned" : 7,
            "selection_type_for_partitions_leaders_pruned" : "RANDOM",
            "max_message_drops" : 1,
            "number_of_configs_pruned" : 10,
            "selection_type_for_configs_pruned" : "RANDOM",
            "step3_paper_execution": True,
            "with_replacement" : False,
        },
    2 : {
            "number_of_nodes" : 4,
            "number_of_twins" : 1,
            "rounds" : 10,
            "number_of_partition" : 3,
            "leaders_only_faulty" : False,
            "number_of_partitions_pruned" : 4,
            "selection_type_for_partitions" : "RANDOM",
            "number_of_partitions_leaders_pruned" : 4,
            "selection_type_for_partitions_leaders_pruned" : "RANDOM",
            "max_message_drops" : 1,
            "number_of_configs_pruned" : 10,
            "selection_type_for_configs_pruned" : "RANDOM",
            "step3_paper_execution": True,
            "with_replacement" : True,
    },
    3 : {
            "number_of_nodes" : 4,
            "number_of_twins" : 1,
            "rounds" : 7,
            "number_of_partition" : 3,
            "leaders_only_faulty" : True,
            "number_of_partitions_pruned" : 4,
            "selection_type_for_partitions" : "RANDOM",
            "number_of_partitions_leaders_pruned" : 7,
            "selection_type_for_partitions_leaders_pruned" : "RANDOM",
            "max_message_drops" : 1,
            "number_of_configs_pruned" : 10,
            "selection_type_for_configs_pruned" : "RANDOM",
            "step3_paper_execution": True,
            "with_replacement" : False,
    },
    4 : {
            "number_of_nodes" : 7,
            "number_of_twins" : 2,
            "rounds" : 7,
            "number_of_partition" : 3,
            "leaders_only_faulty" : True,
            "number_of_partitions_pruned" : 4,
            "selection_type_for_partitions" : "RANDOM",
            "number_of_partitions_leaders_pruned" : 7,
            "selection_type_for_partitions_leaders_pruned" : "RANDOM",
            "max_message_drops" : 1,
            "number_of_configs_pruned" : 10,
            "selection_type_for_configs_pruned" : "RANDOM",
            "step3_paper_execution": True,
            "with_replacement" : False,
        },
    
    5 : {
            "number_of_nodes" : 4,
            "number_of_twins" : 1,
            "rounds" : 10,
            "number_of_partition" : 4,
            "leaders_only_faulty" : True,
            "number_of_partitions_pruned" : 4,
            "selection_type_for_partitions" : "RANDOM",
            "number_of_partitions_leaders_pruned" : 10,
            "selection_type_for_partitions_leaders_pruned" : "RANDOM",
            "max_message_drops" : 1,
            "number_of_configs_pruned" : 10,
            "selection_type_for_configs_pruned" : "RANDOM",
            "step3_paper_execution": False,
            "with_replacement" : False,
        },
}
