config_tests = {
    "number_of_nodes" : 4,
    "number_of_twins" : 1,
    "rounds" : 10,
    "number_of_partition" : 3,
    "leaders_only_faulty" : False,
    "number_of_partitions_pruned" : 4,
    "selection_type_for_partitions" : "RANDOM",
    "number_of_partitions_leaders_pruned" : 4,
    "selection_type_for_partitions_leaders_pruned" : "RANDOM",
    "max_message_drops" : 1,
    "number_of_configs_pruned" : 1,
    "selection_type_for_configs_pruned" : "RANDOM",
    "with_replacement" : True,
}